version: 2
jobs:
  prep:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - checkout
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          keys:
            - npm-deps{{ checksum "package.json" }}

  lint:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Linting code
          command: npm run lint

  json:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Run test [JSON]
          command: npm run test-json

  semantic-release:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Running semantic-release
          command: npm run semantic-release || true

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - prep
      - lint:
          requires:
            - prep
      - json:
          requires:
            - prep
      - semantic-release:
          requires:
            - json